name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move api-key.js
        run: |
          if [ -f "./api-key.js" ] && [ "./api-key.js" != "./api-key.js" ]; then
            mv ./api-key.js .
          fi

      - name: Create api-key.js
        run: |
          echo "export const apiKey = '${{ secrets.API_KEY }}';" > ./api-key.js
          echo "const photosApiKey = '${{ secrets.PHOTOS_API_KEY }}';" >> ./api-key.js
          echo "export const googleApikey = '${{ secrets.GOOGLE_API_KEY }}';" >> ./api-key.js
          echo "export const googleSearchEngineId = '${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}';" >> ./api-key.js

      - name: Configure Git user
        run: |
          git config --global user.email "naomiokelue2002@gmail.com"
          git config --global user.name "Chukwufumnaya"

      - name: Fetch all branches
        run: git fetch --all

      - name: Ensure gh-pages branch exists
        run: |
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initialize gh-pages branch"
            git push origin gh-pages
          fi

      - name: Add api-key.js to gh-pages branch
        run: |
          git add -f ./api-key.js
          git commit -m "Add api-key.js with API keys"
          git push origin gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .